services:
  pb:
    container_name: pb
    restart: unless-stopped
    ports:
      - "8090:8090"
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./pocketbase/pb_data:/pb_data
